export default {
  coaching: {
    pricing: [
      {
        package: 'Junior (U-10) Group Lessons',
        price: 80,
        lessons: 4,
        players: 'minimum two players',
        length: '1 hour',
      },
      {
        package: 'Junior (U-10) One-on-One Lessons',
        price: 120,
        lessons: 4,
        players: 'one on one',
        length: '1 hour',
      },
      {
        package: 'Adult (U-10) One-on-One Lessons',
        price: 140,
        lessons: 4,
        players: 'one on one',
        length: '1 hour',
      },
    ],
    instructors: [
      {
        image: '/daniel_rutenberg.JPG',
        name: 'Daniel Rutenberg',
        education: [
          'Bachelor Degree in Business Administration',
          'Masters in Business Administration',
          'International Direct Marketer of the Year 2007',
        ],
        background: [
          'USATT 2012 Paralympic Coach of the Year',
          'USATT Junior Advisory Committee - Member',
          'USATT Coaching Adivsory Committee - Member',
          'USATT Para Table Tennis Task Force - Staff Liaison',
          '2010-2012 USATT Paralympic National Team Coach',
          'ITTF PTT Level 1 Coach Certification',
          'ITTF PTT Course Conductor',
          'Active USATT member',
          'USATT certified Umpire',
          'USATT National Coach',
          'Specializing in Junior training',
          'USATT 2010 Paralympic Coach of the Year',
          'USATT 2009 Paralympic Coach of the Year',
          '2009 ParaPanAmerican Table Tennis Championship, Margarita Island, Venezuela - Team USA Head Coach',
          'Selected as one of five finalists for the Volunteer Coach of the Year 2005 U.S. Olympic Committee\'s (USOC)  Coach of the Year Program',
          '2005 USATT Volunteer Coach of the Year',
          '2007, 2008 and 2009 instructor at Tzu Chi Foundation U.S. - School',
          '2005-2013 Maccabi Games Team Dallas - Table Tennis Head Coach',
          '2005 & 2006 Sport Information Supervisor NCTTA and ACIU Collegiate Championship',
          '1989 Created Table Tennis Club at Syracuse University',
          '1974-1979 Played for Venezuelan Junior Table Tennis team',
        ],
      },
      {
        image: '/nelson_ramos.JPG',
        name: 'Nelson Ramos',
        education: [
          'Dallas / Ft. Worth Table Tennis Club',
          'Heights Recreation Center - Richardson, TX',
          'Irving Recreation Center - Irving, TX',
          'Jewish Community Center - Dallas, TX',
          'Lewisville Table Tennis Club - Lewisville, TX',
          'International Federation of Table Tennis since 1988',
          'United States Association of Table Tennis since 1987',
        ],
        background: [
          '2011 DFWTT Spring Open: 2nd Place - Class A Singles / 3rd Place - Class A Doubles,',
          '2011 Texas Winter Games: 3rd Place - Class A Singles / 2nd Place - Class A Doubles',
          '2010 DFWTT Fall Open: 3rd Place - Class A Singles / 2010 DFWTT Spring Open',
          '2010 Texas Winter Games: 1st Place - U2400 / 2nd Place - U2400',
          '2009 DFWTT Fall Open: 2nd Place - U2400',
          '2005 Double Ten: 1st Place - Class A Doubles',
          '2004 DFWTT Fall Open: 1st Place - Class A Singles',
          '2003 DFWTT Summer RR: 2nd Place - Class A Singles /  2nd Place - Class A Doubles',
        ],
      },
    ],
  },
}